### ISSUE TITLE
[🐛] Youtube link preview not working correctly on iOS

### ISSUE THREAD

**Issue by suretarget** [flyerhq/react-native-link-preview#12]
### Issue
On iOS it only shows 'Youtube - Share your videos with friends family and the world'. It's **working perfectly on Android** with title, description and a preview image.

### Reproduce
1. `yarn add @flyerhq/react-native-link-preview`
2. `import { LinkPreview } from '@flyerhq/react-native-link-preview'`
3. `<LinkPreview text='This link https://www.youtube.com/watch?v=dpw9EHDh2bM can be extracted from the text' />`

### What I tried
Testing in both Simulator and real device (iPhone X). And I got only a youtube title, no description and no preview image.

### Environment
<details>
  <summary>Click to expand!</summary>

```
System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 247.37 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

</details>

Thank you!

### Updated 
Change the user-agent header fixed the issue.
> headers: {
>      "user-agent": "googlebot"
> },
>

**Comment by demchenkoalex** [comment]
Hi @suretarget we will consider adding `user-agent` to the library itself, thanks for the info!

**Comment by demchenkoalex** [comment]
Added `user-agent` in v1.2.0
