### ISSUE TITLE
Spotify link preview not returning anything

### ISSUE THREAD

**Issue by getXPLORA** [flyerhq/react-native-link-preview#16]
when I insert a Spotify link as a text string, the only thing returned is the link, no previews or logo. Is this an issue everyone is having ?

**Comment by demchenkoalex** [comment]
HI @getXPLORA probably the same issue as specified here - https://github.com/flyerhq/react-native-link-preview/issues/15. Some services would not return preview data for an unidentified client, this library is a good start for normal pages, but will not work for web applications like Twitter, Facebook and apparently Spotify. Btw, https://spotify.com should work. But a link to a song or something rather will require backend solution as mentioned in https://github.com/flyerhq/react-native-link-preview/issues/15.

**Comment by getXPLORA** [comment]
great @demchenkoalex  thanks for the response !
