### ISSUE TITLE
URLs with '@' and other allowed characters are not parsed correctly

### ISSUE THREAD

**Issue by ipakhomov** [flyerhq/react-native-link-preview#18]
Looks like URLs that contain `@` or some other valid characters are not fully parsed.

For example, the URL https://www.npmjs.com/package/@flyerhq/react-native-link-preview results with the following link preview:

<details>

![image](https://user-images.githubusercontent.com/15145582/129480724-8792474c-b584-4d5a-8495-7131cb10afed.png)

</details>

And here is the expected result:

<details>

![image](https://user-images.githubusercontent.com/15145582/129480816-a01c461a-4991-46e8-a191-a12e5e25e8d8.png)

</details>

I suppose the [link regex](https://github.com/flyerhq/react-native-link-preview/blob/main/src/utils.ts#L202) should be extended by [other valid URL characters](https://stackoverflow.com/a/7109208/6617082). 

Or, alternatively, the ability to pass custom regex could be added.

PS.: Thank you for your library!

**Comment by demchenkoalex** [comment]
Hi @ipakhomov, thanks for letting us know! Do you have a specific REGEX in mind? I have found this one which might be better that what we currently have `((http|ftp|https):\/\/)?([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?`. Hard to find something that will work 100% cases. For example I learned that both current and new regex I pasted here will match emails, e.g. alex@flyer.chat where flyer.chat will be matched.

**Comment by demchenkoalex** [comment]
Released new REGEX in [v1.3.8](https://github.com/flyerhq/react-native-link-preview/releases/tag/v1.3.8) in the meantime

**Comment by ipakhomov** [comment]
@demchenkoalex thank you for the prompt response! 

I agree, finding a good regex for URLs is pretty hard. I think the regex you suggested should cover many cases, but you can also pick the best here: https://mathiasbynens.be/demo/url-regex. For example `(https?|ftp)://(-\.)?([^\s/?\.#-]+\.?)+(/[^\s]*)?` looks compact and passing the most of crucial tests.

**Comment by demchenkoalex** [comment]
Yeah, I tried everything on that page and nothing really worked for my tests. Plus we need to match urls like apple.com so this REGEX doesn't work too :( I guess the only problem will be emails, but we can do an email check before the url one I think

**Comment by demchenkoalex** [comment]
Released email ignore in [v1.4.0](https://github.com/flyerhq/react-native-link-preview/releases/tag/v1.4.0)

**Comment by demchenkoalex** [comment]
Updated to `v1.4.1`, previous release is broken
