### ISSUE TITLE
Can I limit the amount of data fetched when previewing a URL?

### ISSUE THREAD

**Issue by TPXP** [flyerhq/react-native-link-preview#22]
We use this module to show link previews for links posted in our app and it works great. Users can type any link in the textbox and it will show a preview of the link before the post is sent.

However, we've found that if a user types a link to a huge file (for example, [an Ubuntu ISO](https://releases.ubuntu.com/20.04.3/ubuntu-20.04.3-desktop-amd64.iso)), the app will download the whole file since it makes a `fetch` call on the URL.
https://github.com/flyerhq/react-native-link-preview/blob/main/src/utils.ts#L80

As can be seen in Flipper:
![image](https://user-images.githubusercontent.com/56550972/138474985-fb084cfa-25df-4f4c-a276-7883737a1b5e.png)

Is there a way to stop the download after fetching obviously too much data, say 1MB? Fetching too much/infinite data could cause an app crash by using too much memory. Granted, we can limit the impact of this by fetching the data server-side and passing `previewData`, in which case only the post sender would fetch that much data. Yet if we could avoid that behaviour, that would be great too.

**Comment by ammarahm-ed** [comment]
@TPXP @demchenkoalex A simple way to do this would be:

```ts
    let abortControllerTimeout: NodeJS.Timeout = null;
    const abort = new AbortController();
    // Abort fetch request after 5 seconds.
    abortControllerTimeout = setTimeout(abort.abort, 5000);
    const response = await fetch(url, {
      headers: {
        'User-Agent':
          'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
      },
      signal: abort.signal
    });
   clearTimeout(abortControllerTimeout);

  
```
Ofcourse the timeout can be modified. I think 5 seconds is enough for a normal request to fetch data but it can be more in case of very slow connections.

**Comment by ammarahm-ed** [comment]
I have updated the example to something that actually works.

**Comment by demchenkoalex** [comment]
hey @ammarahm-ed please do, thank you! :)

**Comment by demchenkoalex** [comment]
Released in [v.1.6.0](https://github.com/flyerhq/react-native-link-preview/releases/tag/v1.6.0). Thanks guys!

**Comment by shawarmaz** [comment]
is it possible to know whether or not the request timed out ? currently it's just returning an empty object. Which could be confused with "succeeded but empty"
