### ISSUE TITLE
LayoutAnimation: consider including react-native-reanimated

### ISSUE THREAD

**Issue by Hirbod** [flyerhq/react-native-link-preview#24]
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/layout_animations

And maybe make those animations configureable. I understand that you want to keep dependencies low, but Reanimated is like the standard toolset for every app I know.

**Comment by demchenkoalex** [comment]
Hey, thanks for the suggestion! I had thoughts to include `react-native-reanimated` as a dependency to all projects we have here, but then I remembered how React Navigation actually removed it, and in large projects reanimated is usually not being updated (I bet a lot of people are still on v1) so I am not sure about that now..

**Comment by Hirbod** [comment]
For now, it seems like LayoutAnimation by Reanimated is broken on FlatLists. It just works for the visible, unscrolled part and not for the overflowed. I would consider it unstable for now.

I think we should keep an eye on it. Reanimated is actually kinda the bare metal standard nowadays, even though I am not 100% happy with the v2 performance at every aspect, but I am sure it will be super stable soon.

**Comment by demchenkoalex** [comment]
Will close this for now, but discussion can be continued later.
