### ISSUE TITLE
Amazon links don't preview correctly

### ISSUE THREAD

**Issue by babyrusa** [flyerhq/react-native-link-preview#26]
Hi guys,

I've tested out a few different links and only Amazon links don't show up correctly. ie: https://www.amazon.com/Squishmallow-14-Inch-Koala-Plush-Ultrasoft/dp/B0973FS5R9 (see attached image). I tried another preview library but the result was the same too so I think this is something with Amazon product links but does anyone know what  I can add to fix this?
![image](https://user-images.githubusercontent.com/57869783/156124983-cc97b549-dfda-4f87-be76-d0be1697c2b7.png)

**Comment by demchenkoalex** [comment]
Yep, that's right. Ideally libraries for link preview work on the backend side, where you can parse twitter/instagram/Facebook posts as well as customary handle any of non-standard sites like amazon. This library is the maximum you can get on a pure frontend. Unfortunately, not all websites are following basic rules of the meta tags, so sometimes you'll get this.
