### ISSUE TITLE
Request: option to not display the link

### ISSUE THREAD

**Issue by diamondhandapp** [flyerhq/react-native-link-preview#28]
Hello, any chance we can add an option to not display the actual link? In my use case the link is redundant.

**Comment by bradzickafoose** [comment]
+1 

I use a separate component to handle displaying the message text that is passed into `<LinkPreview text={text} />`. It would be cool to have have a boolean flag on <LinkPreview displayText={false} text={text} /> to disable displaying the message text that is passed into the text prop which displays above the link preview and instead have the component only render the link's title, description, and image.

**Comment by shawarmaz** [comment]
@bradzickafoose 
actually, this is currently feasible

```js
<LinkPreview
  text={shareBody}
  metadataTextContainerStyle={{ display: 'none' }}
  metadataContainerStyle={{ display: 'none' }}
  textContainerStyle={{ display: 'none' }}
/>

```
