### ISSUE TITLE
App terminated at specific url (Android issue)

### ISSUE THREAD

**Issue by jwAndroid** [flyerhq/react-native-link-preview#41]
For example, URL ("https://developer.android.com") put it in, it's Android development environment Shutdown

`
<LinkPreview text='https://developer.android.com' />
`

how to i do?

**Comment by demchenkoalex** [comment]
<img width="736" alt="Screenshot 2022-06-29 at 11 23 53" src="https://user-images.githubusercontent.com/14123304/176401989-1d6c4007-7162-4e87-b8d8-2a3a523a2708.png">

this is what I see in the example app, no crashes. Will you be able to debug and give an exact reason for a crash?

**Comment by jwAndroid** [comment]
When entering a link("https://developer.android.com") , a runtime error occurs.
It is difficult to debug because no error log was found.

Put the URL("https://developer.android.com")) , app shutting down the app without any logs

![aseg](https://user-images.githubusercontent.com/67754570/176477914-fe52c427-3179-48c9-9eb4-7e3a296758fd.png)

**code App.tsx**
`
import { View } from 'react-native';
import { LinkPreview } from '@flyerhq/react-native-link-preview';

export default function App() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <LinkPreview text="https://developer.android.com" />
    </View>
  );
}
`
**app.json**
`
{
  "expo": {
    "name": "linkPreview",
    "slug": "linkPreview",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
`
install 
"dependencies": {
...
"@flyerhq/react-native-link-preview": "^1.6.0",
}

The important thing is that it's hard to find where runtime error happened.

**Comment by jwAndroid** [comment]
Thank you for your answer

**Comment by demchenkoalex** [comment]
was it resolved? you can find logs on Android using logcat, to debug a runtime error
