### ISSUE TITLE
How to get image and link metadata side by side?

### ISSUE THREAD

**Issue by KrisLau** [flyerhq/react-native-link-preview#46]
I've tried a combination of container styles and tried using the renderLinkPreview method but neither of them seemed to work. What Im tying to achieve looks something like this: 
![image](https://user-images.githubusercontent.com/46275463/198722385-6dc6bb99-fd3a-41cc-95ff-c625561bc715.png)

**Comment by demchenkoalex** [comment]
`renderLinkPreview` is a function that returns whatever view you write. How Is this not possible? Just use `previewData` provided by that function and build your own layout.

**Comment by KrisLau** [comment]
@demchenkoalex I figured it out sorry! I was having a problem because I didn't put in a null check so the renderLinkPreview was just returning a blank component.
