### ISSUE TITLE
Prevent opening link and add longPress event

### ISSUE THREAD

**Issue by octopus-travels** [flyerhq/react-native-link-preview#60]
Hi, I'd like to add the longPress event to the preview (wrapped inside Pressable), but it always opens the link. Is there a way that I could prevent the title/text or image opening the link and wrap the content inside Pressable, so the I can open up a different menu on longPress?

**Comment by demchenkoalex** [comment]
Hey, you can do your own layout using `renderLinkPreview`

**Comment by octopus-travels** [comment]
Thank for the reply. I had tried this before, but didn't work as I had made a silly mistake by wrapping the whole `<LinkPreview>` component with `<Pressable>` instead just the `renderLinkPreview` layout. However, `renderLinkPreview` provides much flexibility in creating a custom layout. Thanks again.
